#Vocabulario del Cluster

LATIDO = "LATIDO"
QUIEN = "QUIEN"
ELECCION = "ELECCION"
COORDINADOR = "COORDINADOR"
REPLICA = "REPLICA"
PUESTA_AL_DIA = "PUESTA_AL_DIA"

#motivo de replicacion
EPOCA_VIEJA = "EPOCA_VIEJA"
ATRASADO = "ATRASADO"
DUPLICADA = "DUPLICADA"
ILEGAL = "ILEGAL"
TIPO_DESCONOCIDO = "TIPO_DESCONOCIDO"

AL_DIA = (None, DUPLICADA)
